version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "helm" 
    directory: "/charts/rstuf-demo/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "deps-rstuf-demo"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
