version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "helm" 
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "deps"
      include: "scope"
