apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rstuf-worker.fullname" . }}
  labels:
    {{- include "rstuf-worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rstuf-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rstuf-worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rstuf-worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}     
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.gcp.applicationCredentials }}
            - name: gcp-credentials-volume
              mountPath: /run/secrets/gcp-credentials
              readOnly: true
            {{- end }}
            {{- if .Values.onlineKeyFile }}
            {{- range .Values.onlineKeyFile }}
            - name: {{ .keyid | printf "%.7s" }}-keyfile-volume
              mountPath: /run/secrets/{{ .keyid }}
              subPath: {{ .keyid }}
            {{- end }}
            {{- end }}
          env:
            - name: RSTUF_BROKER_SERVER
              value: {{ .Values.backend.brokerServer | quote }}
            - name: RSTUF_REDIS_SERVER
              value: {{ .Values.backend.redisServer | quote }}
            - name: RSTUF_DB_SERVER
              value: {{ .Values.backend.dbServer | quote }}
            - name: RSTUF_STORAGE_BACKEND
              value: {{ required "storage.type must be 'AWSS3' or 'LocalStorage'." .Values.storage.type | quote }}
            {{- if eq .Values.storage.type "LocalStorage" }}
            - name: RSTUF_LOCAL_STORAGE_BACKEND_PATH
              value: {{ required "storage.backendPath is required when storage.type is 'LocalStorage'." .Values.storage.storagePath | quote }}
            {{- end }}
            {{- if .Values.onlineKeyDir }}
            - name: RSTUF_ONLINE_KEY_DIR
              value: {{ .Values.onlineKeyDir | quote }}
            {{- end }}
            {{- if eq .Values.storage.type "AWSS3" }}
            - name: RSTUF_AWS_STORAGE_BUCKET
              value: {{ required "storage.s3Bucket is required when storage.type is 'AWSS3'." .Values.storage.s3Bucket | quote }}
            {{- end }}
            {{- if .Values.aws.accessKey }}
            - name: RSTUF_AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKey | quote }}
            {{- end }}
            {{- if .Values.aws.secretKey  }}
            - name: RSTUF_AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretKey | quote }}
            {{- end }}
            {{- if .Values.aws.region }}
            - name: RSTUF_AWS_DEFAULT_REGION
              value: {{ .Values.aws.region | quote }}
            {{- end }}
            {{- if .Values.aws.endpoint }}
            - name: RSTUF_AWS_ENDPOINT_URL
              value: {{ .Values.aws.endpoint | quote }}
            {{- end }}
            {{- if .Values.aws.s3_object_acl }}
            - name: RSTUF_AWS_S3_OBJECT_ACL
              value: {{ .Values.aws.s3_object_acl | quote }}
            {{- end }}
            {{- if .Values.backend.redisPort }}
            - name: RSTUF_REDIS_SERVER_PORT
              value: {{ .Values.backend.redisPort | quote }}
            {{- end }}
            {{- if .Values.backend.redisDbResult }}
            - name: RSTUF_REDIS_SERVER_DB_RESULT
              value: {{ .Values.backend.redisDbResult | quote }}
            {{- end }}
            {{- if .Values.backend.redisDbSettings }}
            - name: RSTUF_REDIS_SERVER_DB_REPO_SETTINGS
              value: {{ .Values.backend.redisDbSettings | quote }}
            {{- end }}
            {{- if .Values.backend.lockTimeOut }}
            - name: RSTUF_LOCK_TIMEOUT
              value: {{ .Values.backend.lockTimeOut | quote }}
            {{- end }}
            {{- if .Values.gcp.applicationCredentials }}
            - name: RSTUF_GOOGLE_APPLICATION_CREDENTIALS
              value: /run/secrets/gcp-credentials/ac.json
            {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.gcp.applicationCredentials }}
        - name: gcp-credentials-volume
          secret:
            secretName: gcp-credentials
        {{- end }}
        {{- if .Values.onlineKeyFile }}
        {{- range .Values.onlineKeyFile }}
        - name: {{ .keyid | printf "%.7s" }}-keyfile-volume
          secret:
            secretName: {{ .keyid }}-keyfile-secret
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
