{{- if and (and .Values.s3Gateway.enabled (eq .Values.storage.type "AWSS3")) .Values.s3Gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rstuf-worker.s3GatewayFullname" . }}
  labels:
    {{- include "rstuf-worker.s3GatewayLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rstuf-worker.s3GatewayFullname" . }}
  minReplicas: {{ .Values.s3Gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.s3Gateway.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.s3Gateway.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.s3Gateway.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.s3Gateway.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.s3Gateway.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
