# templates/secrets.yaml
{{- if and (.Values.onlineKeyDir) (.Values.onlineKeyFile) }}
{{- range .Values.onlineKeyFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .keyid }}-keyfile-secret
type: Opaque
data:
  {{ .keyid }}: {{ .pem | quote }}
---
{{- end }}
{{- end }}