{{- if and (.Values.onlineKeyDir) (.Values.onlineKeyFile) }}
{{- range .Values.onlineKeyFile }}
{{- if not .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .keyid }}-keyfile-secret
type: Opaque
data:
  {{ .keyid }}: {{ .pem | quote }}
{{- end }}
{{- end }}
{{- end }}
