# templates/secrets.yaml
# gcp.googleApplicationCredentials
{{- if .Values.gcp.applicationCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
type: Opaque
data:
  ac.json: {{ .Values.gcp.applicationCredentials | quote }}
{{- end }}
# onlineKeyDir and key file
{{- if and (.Values.onlineKeyDir) (.Values.onlineKeyFile) }}
---
{{- range .Values.onlineKeyFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .keyid }}-keyfile-secret
type: Opaque
data:
  {{ .keyid }}: {{ .pem | quote }}
---
{{- end }}
{{- end }}