{{- if and (and .Values.s3Gateway.enabled (eq .Values.storage.type "AWSS3")) .Values.s3Gateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rstuf-worker.s3GatewayServiceAccountName" . }}
  {{- with .Values.s3Gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rstuf-worker.s3GatewayLabels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.s3Gateway.serviceAccount.automount }}
{{- end }}
