apiVersion: v2
name: rstuf-demo
description: RSTUF Demo deploying RSTUF services and infrastructure services. This deployment is not recommended for production.
version: 0.3.14
maintainers:
  - name: kairoaraujo

dependencies:
  - name: rstuf-api
    version: 0.2.5
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: rstuf-worker
    version: 0.4.3
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: postgresql
    version: 16.7.27
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgres.enabled
  - name: redis
    version: 22.0.7
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: valkey
    version: 3.0.31
    repository: "https://charts.bitnami.com/bitnami"
    condition: valkey.enabled
  - name: rabbitmq
    version: 16.0.14
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: mysql
    version: 14.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: localstack
    version: 0.6.25
    repository: "https://localstack.github.io/helm-charts"
    condition: localstack.enabled
