apiVersion: v2
name: rstuf-demo
description: RSTUF Demo deploying RSTUF services and infrastructure services. This deployment is not recommended for production.
version: 0.3.15
maintainers:
  - name: kairoaraujo

dependencies:
  - name: rstuf-api
    version: 0.2.5
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: rstuf-worker
    version: 0.4.3
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: postgres
    version: 0.19.6
    repository: "https://cloudpirates-io.github.io/helm-charts"
    condition: postgres.enabled
  - name: valkey
    version: 0.10.0
    repository: "https://valkey.io/valkey-helm"
    condition: valkey.enabled
  - name: localstack
    version: 0.6.25
    repository: "https://localstack.github.io/helm-charts"
    condition: localstack.enabled
