apiVersion: v2
name: rstuf-demo
description: RSTUF Demo deploying RSTUF services and infrastructure services. This deployment is not recommended for production.
version: 0.3.5
maintainers:
  - name: kairoaraujo

dependencies:
  - name: rstuf-api
    version: 0.2.2
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: rstuf-worker
    version: "0.3.2"
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: postgresql
    version: 16.6.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgres.enabled
  - name: redis
    version: 20.11.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: valkey
    version: 2.4.7
    repository: "https://charts.bitnami.com/bitnami"
    condition: valkey.enabled
  - name: rabbitmq
    version: 15.4.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: mysql
    version: 12.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: localstack
    version: 0.6.23
    repository: "https://localstack.github.io/helm-charts"
    condition: localstack.enabled
