apiVersion: v2
name: rstuf-demo
description: RSTUF Demo deploying RSTUF services and infrastructure services. This deployment is not recommended for production.
version: 0.3.11
maintainers:
  - name: kairoaraujo

dependencies:
  - name: rstuf-api
    version: 0.2.4
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: rstuf-worker
    version: 0.4.2
    repository: "https://repository-service-tuf.github.io/helm-charts"
  - name: postgresql
    version: 16.6.6
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgres.enabled
  - name: redis
    version: 20.13.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: valkey
    version: 3.0.3
    repository: "https://charts.bitnami.com/bitnami"
    condition: valkey.enabled
  - name: rabbitmq
    version: 16.0.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: mysql
    version: 12.3.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: localstack
    version: 0.6.23
    repository: "https://localstack.github.io/helm-charts"
    condition: localstack.enabled
