name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: v3.14.4

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f
        with:
          version: "3.14.0"
          yamale_version: "6.1.0"

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint --target-branch ${{ github.event.repository.default_branch }} \
          --chart-repos=cloudpirates=https://cloudpirates-io.github.io/helm-charts \
          --chart-repos=valkey=https://valkey.io/valkey-helm \
          --chart-repos=rstuf=https://repository-service-tuf.github.io/helm-charts \
          --chart-repos=localstack=https://localstack.github.io/helm-charts

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} \
          --excluded-charts rstuf-demo

      - name: Run chart-testing (install rstuf-demo)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ "$changed" == *"charts/rstuf-demo"* ]]; then
            ct install --charts charts/rstuf-demo \
            --namespace rstuf \
            --release-name rstuf-demo \
            --chart-repos=cloudpirates=https://cloudpirates-io.github.io/helm-charts \
            --chart-repos=valkey=https://valkey.io/valkey-helm \
            --chart-repos=rstuf=https://repository-service-tuf.github.io/helm-charts \
            --chart-repos=localstack=https://localstack.github.io/helm-charts \
            --helm-extra-args="--create-namespace" \
            --helm-extra-set-args="--set rstuf-worker.initContainers=null,rstuf-api.initContainers=null"
          fi
